### ISSUE TITLE
statement.object.definition.choices creates 400 error

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#33]
I think this might be an issue with the JSON schema.

consider this statement (build from xAPI spec examples):

```
 {
    "actor":{
        "objectType": "Agent",
        "name":"Project Tin Can API",
        "mbox":"mailto:user@example.com"
    },
    "verb":{
        "id":"http://example.com/xapi/verbs#sent-a-statement",
        "display":{
            "en-US":"sent"
        }
    },
    "object":{
        "id":"http://example.com/xapi/activity/pingpong",
        "definition": {
            "description": {
                "en-US": "Order players by their pong ladder position:"
            },
            "type": "http://adlnet.gov/expapi/activities/cmi.interaction",
            "interactionType": "sequencing",
            "correctResponsesPattern": [
                "tim[,]mike[,]ells[,]ben"
            ],
            "choices": [
                {
                    "id": "tim",
                    "description": {
                        "en-US": "Tim"
                    }
                },
                {
                    "id": "ben", "description": {
                        "en-US": "Ben"
                    }
                },
                {
                    "id": "ells",
                    "description": {
                        "en-US": "Ells"
                    }
                },
                {
                    "id": "mike",
                    "description": {
                        "en-US": "Mike"
                    }
                }
            ]
        }
    }
};
```
* Statement passes with param `object.definition.choices` when POSTing to https://lrs.adlnet.gov/xAPI
* Statement fails with param `object.definition.choices`  when POSTing to lxHive
*  Statement fails with empty array `object.definition.choices`  when POSTing to lxHive
* Statement passes **without** param `object.definition.choices`  when POSTing to lxHive

the rather cryptic error: 
```
[2015-09-08 04:58:25] SlimMonoLogger.ERROR: exception 'API\Validator\Exception' with message 'Statements do not validate. Violations: [] object value found, but an array is required [object] the property actor is required [object] the property verb is required [object] the property object is required [object.id] does not match the regex pattern [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{8} [object] The property definition is not defined and the definition does not allow additional properties [object] failed to match exactly one schema [object] the property objectType is required [object.id] string value found, but a null is required [object.object] matched a schema which it should not [object.definition.choices] array value found, but an object is required [object] the property openid is required [object] the property mbox is required [object] the property mbox_sha1sum is required [object] the property account is required [object] failed to match all schemas [object] The property id is not defined and the definition does not allow additional properties [object] the property member is required [] failed to match exactly one schema ' in /www/lxHive/src/xAPI/Validator/V10/Statement.php:46 Stack trace: #0 /www/lxHive/src/xAPI/Validator/V10/Statement.php(75): API\Validator\V10\Statement->throwErrors('Statements do n...', Array) #1 /www/lxHive/src/xAPI/Resource/V10/Statements.php(122): API\Validator\V10\Statement->validatePostRequest(Object(Slim\Http\Request)) #2 /www/lxHive/public/index.php(217): API\Resource\V10\Statements->post() #3 [internal function]: {closure}('statements') #4 /www/lxHive/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #5 /www/lxHive/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch() #6 /www/lxHive/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #7 /www/lxHive/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #8 /www/lxHive/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call() #9 /www/lxHive/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call() #10 /www/lxHive/public/index.php(251): Slim\Slim->run() #11 {main} [] []
```

**Comment by RoboSparrow** [comment]
added test [statements-objects.spec.js](http://bcdev.brightcookie.com.au/joerg/lxJasmine/Jasmine/SpecRunner.Statements-Object.html)

**Comment by sraka1** [comment]
Error says "[object.definition.choices] array value found, but an
object is required".

Fixing.


torek, 08. september 2015 je oseba Joerg Boeselt <notifications@github.com>
napisala:

> added test statements-objects.spec.js
> <http://bcdev.brightcookie.com.au/joerg/lxJasmine/Jasmine/SpecRunner.Statements-Object.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brightcookie/lxHive/issues/33#issuecomment-138441108>.
>


-- 
Lp,
Jakob
